// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Packet

import "strconv"

type PacketErrorCode int8

const (
	PacketErrorCodeNone          PacketErrorCode = 0
	PacketErrorCodeReconnectFail PacketErrorCode = 1
)

var EnumNamesPacketErrorCode = map[PacketErrorCode]string{
	PacketErrorCodeNone:          "None",
	PacketErrorCodeReconnectFail: "ReconnectFail",
}

var EnumValuesPacketErrorCode = map[string]PacketErrorCode{
	"None":          PacketErrorCodeNone,
	"ReconnectFail": PacketErrorCodeReconnectFail,
}

func (v PacketErrorCode) String() string {
	if s, ok := EnumNamesPacketErrorCode[v]; ok {
		return s
	}
	return "PacketErrorCode(" + strconv.FormatInt(int64(v), 10) + ")"
}
