// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Packet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserLoginServer struct {
	_tab flatbuffers.Table
}

func GetRootAsUserLoginServer(buf []byte, offset flatbuffers.UOffsetT) *UserLoginServer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserLoginServer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUserLoginServer(buf []byte, offset flatbuffers.UOffsetT) *UserLoginServer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserLoginServer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UserLoginServer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserLoginServer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserLoginServer) UserIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UserLoginServer) MutateUserIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func UserLoginServerStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UserLoginServerAddUserIndex(builder *flatbuffers.Builder, userIndex int32) {
	builder.PrependInt32Slot(0, userIndex, 0)
}
func UserLoginServerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
