// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Packet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserInfoServer struct {
	_tab flatbuffers.Table
}

func GetRootAsUserInfoServer(buf []byte, offset flatbuffers.UOffsetT) *UserInfoServer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserInfoServer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUserInfoServer(buf []byte, offset flatbuffers.UOffsetT) *UserInfoServer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserInfoServer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UserInfoServer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserInfoServer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserInfoServer) UserIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UserInfoServer) MutateUserIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *UserInfoServer) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UserInfoServerStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func UserInfoServerAddUserIndex(builder *flatbuffers.Builder, userIndex int32) {
	builder.PrependInt32Slot(0, userIndex, 0)
}
func UserInfoServerAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func UserInfoServerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
