// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Packet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserConnectDoneServer struct {
	_tab flatbuffers.Table
}

func GetRootAsUserConnectDoneServer(buf []byte, offset flatbuffers.UOffsetT) *UserConnectDoneServer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserConnectDoneServer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUserConnectDoneServer(buf []byte, offset flatbuffers.UOffsetT) *UserConnectDoneServer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserConnectDoneServer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UserConnectDoneServer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserConnectDoneServer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserConnectDoneServer) CurrentTimeMsec() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UserConnectDoneServer) MutateCurrentTimeMsec(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func UserConnectDoneServerStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UserConnectDoneServerAddCurrentTimeMsec(builder *flatbuffers.Builder, currentTimeMsec int64) {
	builder.PrependInt64Slot(0, currentTimeMsec, 0)
}
func UserConnectDoneServerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
