// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Packet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserHeartBeatServer struct {
	_tab flatbuffers.Table
}

func GetRootAsUserHeartBeatServer(buf []byte, offset flatbuffers.UOffsetT) *UserHeartBeatServer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserHeartBeatServer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUserHeartBeatServer(buf []byte, offset flatbuffers.UOffsetT) *UserHeartBeatServer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserHeartBeatServer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UserHeartBeatServer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserHeartBeatServer) Table() flatbuffers.Table {
	return rcv._tab
}

func UserHeartBeatServerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func UserHeartBeatServerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
