// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Packet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserErrorCloseServerNotify struct {
	_tab flatbuffers.Table
}

func GetRootAsUserErrorCloseServerNotify(buf []byte, offset flatbuffers.UOffsetT) *UserErrorCloseServerNotify {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserErrorCloseServerNotify{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUserErrorCloseServerNotify(buf []byte, offset flatbuffers.UOffsetT) *UserErrorCloseServerNotify {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserErrorCloseServerNotify{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UserErrorCloseServerNotify) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserErrorCloseServerNotify) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserErrorCloseServerNotify) ErrorCodeIndex() PacketErrorCode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return PacketErrorCode(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *UserErrorCloseServerNotify) MutateErrorCodeIndex(n PacketErrorCode) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func UserErrorCloseServerNotifyStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UserErrorCloseServerNotifyAddErrorCodeIndex(builder *flatbuffers.Builder, errorCodeIndex PacketErrorCode) {
	builder.PrependInt8Slot(0, int8(errorCodeIndex), 0)
}
func UserErrorCloseServerNotifyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
