// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Packet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserConnectDoneClient struct {
	_tab flatbuffers.Table
}

func GetRootAsUserConnectDoneClient(buf []byte, offset flatbuffers.UOffsetT) *UserConnectDoneClient {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserConnectDoneClient{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUserConnectDoneClient(buf []byte, offset flatbuffers.UOffsetT) *UserConnectDoneClient {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserConnectDoneClient{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UserConnectDoneClient) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserConnectDoneClient) Table() flatbuffers.Table {
	return rcv._tab
}

func UserConnectDoneClientStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func UserConnectDoneClientEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
