// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Packet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserLoginClient struct {
	_tab flatbuffers.Table
}

func GetRootAsUserLoginClient(buf []byte, offset flatbuffers.UOffsetT) *UserLoginClient {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserLoginClient{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUserLoginClient(buf []byte, offset flatbuffers.UOffsetT) *UserLoginClient {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserLoginClient{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UserLoginClient) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserLoginClient) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserLoginClient) AccessToken() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UserLoginClientStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UserLoginClientAddAccessToken(builder *flatbuffers.Builder, accessToken flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(accessToken), 0)
}
func UserLoginClientEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
