// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Packet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserConnectVerifyClient struct {
	_tab flatbuffers.Table
}

func GetRootAsUserConnectVerifyClient(buf []byte, offset flatbuffers.UOffsetT) *UserConnectVerifyClient {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserConnectVerifyClient{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUserConnectVerifyClient(buf []byte, offset flatbuffers.UOffsetT) *UserConnectVerifyClient {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserConnectVerifyClient{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UserConnectVerifyClient) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserConnectVerifyClient) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserConnectVerifyClient) AccessToken() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UserConnectVerifyClientStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UserConnectVerifyClientAddAccessToken(builder *flatbuffers.Builder, accessToken flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(accessToken), 0)
}
func UserConnectVerifyClientEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
