// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Packet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserConnectVerifyServer struct {
	_tab flatbuffers.Table
}

func GetRootAsUserConnectVerifyServer(buf []byte, offset flatbuffers.UOffsetT) *UserConnectVerifyServer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserConnectVerifyServer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUserConnectVerifyServer(buf []byte, offset flatbuffers.UOffsetT) *UserConnectVerifyServer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserConnectVerifyServer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UserConnectVerifyServer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserConnectVerifyServer) Table() flatbuffers.Table {
	return rcv._tab
}

func UserConnectVerifyServerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func UserConnectVerifyServerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
