// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Packet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserInfoClient struct {
	_tab flatbuffers.Table
}

func GetRootAsUserInfoClient(buf []byte, offset flatbuffers.UOffsetT) *UserInfoClient {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserInfoClient{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUserInfoClient(buf []byte, offset flatbuffers.UOffsetT) *UserInfoClient {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserInfoClient{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UserInfoClient) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserInfoClient) Table() flatbuffers.Table {
	return rcv._tab
}

func UserInfoClientStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func UserInfoClientEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
